
variant: elasticsearch7
image:
  repository: "fluent/fluentd-kubernetes-daemonset"
  tag: v1.14.6-debian-loki-1.0
  pullPolicy: "IfNotPresent"

serviceAccount:
  create: true

rbac:
  create: true

fileConfigs:
  01_sources.conf: |-
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

  04_outputs.conf: |-
    <match **>
      @type loki
      url "http://loki:3100/loki/api/v1/push"
      tenant_id "default"
      line_format "json"
      flush_interval 5s
    </match>

metrics:
  serviceMonitor:
    enabled: true

dashboards:
  enabled: true
  labels:
    grafana_dashboard: "1"
