
loki:
  enabled: true
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 30
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 30

promtail:
  enabled: false

fluent-bit:
  enabled: false

grafana:
  enabled: false

logstash:
  enabled: false

filebeat:
  enabled: false
